<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer  */ ?>
<p>Unlock the power of innovation with Elasticsuite! 🚀 </p>
<p>Subscribe to our newsletter now and stay ahead of the curve.</p>
<p>Dive into exclusive insights on our cutting-edge product features, harness the freedom of open source collaboration, and enjoy non-intrusive updates that keep you in the loop without overwhelming your inbox.</p>
<p>Join the Elasticsuite community today – where innovation meets seamless communication. Subscribe and elevate your experience now!</p>
<?= /* @NoEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], '  (() => {
    const script = document.createElement("script");
    script.setAttribute("type", "text/javascript");
    script.src = "https://js.hsforms.net/forms/embed/v2.js";

    script.addEventListener("load", () => {
      hbspt.forms.create({
        region: "na1",
        portalId: "6113121",
        formId: "1b10ec2f-3de4-4a17-b1f5-3826361fadf1",
      });
    });

    document.head.append(script);
  })();', false) ?>
